omegaml/defaults.py
omegaml/runtimes/jobproxy.py
omegaml/runtimes/mixins/gridsearch.py
omegaml/runtimes/mixins/modelmixin.py
omegaml/runtimes/modelproxy.py
omegaml/runtimes/runtime.py
omegaml/tests/test_jobs.py

This refactors _common_kwargs logic from XYProxy implementations to OmegaRuntime, rendering the implementation consistent and ensure the kwargs are always sent by the runtime, not by the choice of the proxy.

refactor _common_kwargs to OmegaRuntime

---

.circleci/config.yml

We execute only the steps required for the unit tests to run. Other steps (run RabbitMQ, start services with Honcho) are commented-out. These will probably be needed down the road, for integration testing. We cache all installed Python packages to speed-up builds. Modifying `requirements` files will rebuild the cache.

Add CircleCI configuration for unit tests

---

omegaml/client/userconf.py
omegaml/tests/test_sklext.py
setup.py

this enables the client api to the managed omegaml platform.
```
from omegaml.client.userconf import get_omega_from_apikey
om = get_omega_from_apikey(userid='USER', apikey='APIKEY', api_url='platform URI')
```

Enable client api

---

.circleci/config.yml
scripts/livetest.sh

- Add Livetest step to CircleCI configuration.
- Completely disable Python env caching. (Caching was not a good idea, because `requirements` files do not pin the version of every recursive dependency. Not a loss, because build speedup was insignificant.)
- Switch to machine executor.

Add Livetest step to CircleCI configuration.

---

docs/source/guide/buckets.rst
omegaml/backends/rawfiles.py
omegaml/celery_util.py
omegaml/mixins/store/promotion.py
omegaml/omega.py
omegaml/restapi/__init__.py
omegaml/restapi/tests/test_api.py
omegaml/restapi/tests/test_api_buckets.py
omegaml/restapi/tests/util.py
omegaml/runtimes/runtime.py
omegaml/store/base.py
omegaml/tests/test_configs.py
omegaml/tests/test_promotion.py
omegaml/tests/util.py

* add the `prompte` operation on datasets and models across Omega instances
* enable the built-in bucket to work properly in the REST API and runtime
Note technically buckets are not required for multiple Omega instances. Buckets however enable logical datasets and model separation within a single database instance (e.g. per user, project etc.)

Promotion api

---

.gitignore
omegaml/__init__.py
omegaml/defaults.py
omegaml/omega.py
omegaml/runtimes/runtime.py

* config.yml can now be in local directory, in user application configuration, global site configuration
* works for all platforms, using appdirs package
* name of config file can be specified using `OMEGAL_CONFIG_FILE` env var
* also fix bucket issue on install, fix bug that prevented celery's eager mode during runtime tests

enable project, user and global config file

---

omegaml/defaults.py
omegaml/mongoshim.py
omegaml/store/base.py
omegaml/store/fastinsert.py
omegaml/util.py

- "Create a shim function, called MongoClient in a new package omegaml/mongoshim.py (omegaml repo), then import that function instead of importing MongoClient directly. This achieves centralization of client configuration as well as reduces maintenance effort if we have to change it; also it removes the need to import settings everywhere we need to use MongoClient." - @miraculixx 
- Check environment variable for Rabbitmq SSL settings

Updates for SSL connections

---

omegaml/client/cli/__init__.py
omegaml/client/cli/catchall.py
omegaml/client/cli/cloud.py
omegaml/client/cli/datasets.py
omegaml/client/cli/jobs.py
omegaml/client/cli/models.py
omegaml/client/cli/runtime.py
omegaml/client/cli/scripts.py
omegaml/client/cli/shell.py
omegaml/client/cloud.py
omegaml/client/docoptparser.py
omegaml/tests/cli/scenarios.py
omegaml/tests/cli/test_cli_datasets.py
omegaml/tests/cli/test_cli_jobs.py
omegaml/tests/cli/test_cli_models.py
omegaml/tests/cli/test_cli_runtime.py
omegaml/tests/cli/test_cli_scripts.py
omegaml/tests/features/cli.feature
omegaml/tests/util.py
omegaml/util.py

this improves and stabilizes the cli significantly, includes extensive test coverage
```
$ om -h
Usage: om <command> [<action>] [<args> ...] [options]
om (models|datasets|scripts|jobs) [<args> ...] [--raw] [--replace] [options]
om runtime [<args> ...] [--async] [options]
om cloud [<args> ...] [options]
om shell [options]
om [-h] [-hh] [--version] [--copyright]
omega|ml command line client
Usage of datasets
om datasets list [<pattern>] [--raw]
om datasets put <path> <name> [--replace]
om datasets get <name> <path>
om datasets drop <name> [--force]
om datasets metadata <name>
Usage of models
om models put <module.callable> <name>
om models list [<pattern>] [--raw]
om models metadata <name>
Usage of runtime
om runtime model <name> <model-action> [<X>] [<Y>] [<kw=value> ...>] [--async] …
```

extend cli

---

omegaml/tests/cli/scenarios.py

scipy >0.1.2 removed deprecated `imsave` causing a test regression on fresh pip install

resolve deprecated scipy dependency

---

.gitignore
omegaml/backends/basemodel.py
omegaml/backends/keras.py
omegaml/backends/package/__init__.py
omegaml/backends/scikitlearn.py
omegaml/backends/tensorflow/tfestimatormodel.py
omegaml/backends/tensorflow/tfkeras.py
omegaml/backends/tensorflow/tfsavedmodel.py
omegaml/client/cli/runtime.py
omegaml/defaults.py
omegaml/mixins/store/modelversion.py
omegaml/mixins/store/promotion.py
omegaml/restapi/__init__.py
omegaml/restapi/tests/test_api.py
omegaml/runtimes/mixins/modelmixin.py
omegaml/runtimes/modelproxy.py
omegaml/store/base.py
omegaml/tasks.py
omegaml/tests/cli/scenarios.py
omegaml/tests/cli/test_cli_runtime.py
omegaml/tests/test_modelversions.py
omegaml/tests/test_promotion.py
omegaml/tests/test_store.py
omegaml/util.py

this enables automated model versioning
Model versioning and multi-model deployment is not new to omegaml but before this required explicit versioning by name.
* the ModelVersion plugin automatically versions models, keeping all versioning accessible from the same Metadata entry
* each model version is represented as its own object, allowing for diffs both across the model itself as well as it the Metadata
* each model version remembers specifics such as gridsearch results, what data and features it was fitted against etc.
* model versioning is transparent to all APIs as it is implemented as an extension to the model store, not as part of a particular backend
* multiple versions can be run at the same time using the runtime api

enabling automated model versioning

---

.gitignore
omegaml/backends/externaldata.py
omegaml/backends/rawfiles.py
omegaml/defaults.py
omegaml/notebook/jobs.py
omegaml/notebook/tasks.py
omegaml/tests/test_jobs.py
setup.py

various enhancements  following community feedback
- externaldata moved from omegaml ee edition to core
- rawfiles improved to enable local path output using get(...,
local=path)
- job run now clears notebook output and stores resulting notebook in
error and ok states (previously only ok states were stored)
- runtime job run returns repr(metadata) instead of full metadata object
like other tasks

add externaldata backend, jobs returns metadata repr, easier rawfiles export

---

omegaml/defaults.py
omegaml/mixins/store/datarevision.py
omegaml/store/base.py
omegaml/tests/test_datarevision.py
omegaml/util.py

This enables automated data revisions for dataframes (currently only when stored in mongodb). 
```
Usage:
om.datasets.put(df, 'mydf', revisions=True)
om.datasets.put(updates_df, 'mydf')
om.datasets.put(updates_df, 'mydf', revision_dt=<dt>)
om.datasets.put(updates_df, 'mydf', tag='tagname')
om.datasets.put(updates_df, 'mydf', delete=True)
updates_df['_delete_'] = True
om.datasets.put(updates_df, 'mydf')
om.datasets.get('mydf')
om.datasets.get('mydf', revision=N|datetime|tag)
om.datasets.get('mydf', changeset=N)
om.datasets.get('mydf', trace_revisions=True)
```

enable automated data revisions

---

omegaml/backends/experiment.py
omegaml/mixins/store/promotion.py
omegaml/notebook/tasks.py
omegaml/runtimes/mixins/taskcanvas.py
omegaml/runtimes/runtime.py
omegaml/tests/core/restapi/test_model_api.py
omegaml/tests/core/test_promotion.py
omegaml/tests/core/test_runtime.py
omegaml/tests/core/test_tracking.py

- experiments now provide a .track(model) method to easily update model
default tracking
- promotion of models to same store works as long as with different
names
- job task handlers now catch errors silently
- task parallel results provide .collect() and .getall() results to
easily return parent tasks
- runtime.require('local') is equivalent to runtime.local(mode=True)
- add tests

various updates

---

omegaml/__init__.py
omegaml/backends/package/tasks.py
omegaml/celery_util.py
omegaml/client/auth.py
omegaml/client/cli/runtime.py
omegaml/defaults.py
omegaml/example/demo/helloworld/helloworld/__init__.py
omegaml/omega.py
omegaml/runtimes/runtime.py
omegaml/store/fastinsert.py
omegaml/store/streams.py
omegaml/tests/mlflow/test_mlflow_models.py
omegaml/util.py
setup.py

this improves on several performance related aspects
* worker performance: by enabling caching of omega instances. configurable in defaults.OMEGA_SETTINGS_CACHE
* session loading: load smarter, avoiding irrelevant tests
to keep ci going, also fixes 
* mlflow latest release caused failures on task exit, invalidating tests even though they ran ok
* pymongo changes in pooling caused fastinsert to attempt reusing closed connections in PickledCollection

Performance gains

---

docs/source/nb/omegaml-tutorial.ipynb
omegaml/__init__.py
omegaml/client/auth.py
omegaml/client/cloud.py
omegaml/client/userconf.py
omegaml/defaults.py
omegaml/mongoshim.py
omegaml/omega.py
omegaml/store/fastinsert.py
omegaml/tests/features/util.py
omegaml/util.py
pip-requirements.txt
setup.py

- mongoshim, defaults: pymongo prefers tls= instead of ssl=
- fastinsert: increase chunksize to increase insert throughput of
smaller dataframes
- pickable mongo collection: support authSource'd credentials
- fix celery dependency

fup to auth env refactorign, upgrades of pymongo, performance tuning

---

omegaml/backends/mlflow/gitprojects.py
omegaml/backends/mlflow/localprojects.py
omegaml/backends/package/localpip.py
omegaml/backends/package/packager.py
omegaml/backends/package/remotepip.py
omegaml/backends/package/tasks.py
omegaml/backends/restapi/script.py
omegaml/backends/virtualobj.py
omegaml/celery_util.py
omegaml/example/demo/helloworld/helloworld/__init__.py
omegaml/runtimes/scriptproxy.py
omegaml/tests/core/restapi/test_script_api.py
omegaml/tests/core/test_package.py
omegaml/tests/core/test_virtualobj.py

- matches how scripts are called to how model actions are called
- enables easier reuse and extension
- enables virtual functions to be saved to and run in om.scripts
- rename package.tasks.NotebookTask to ScriptTask
- fix on_success/on_retry/on_failure handler signature (#239)
- closes #238

runtime.scripts/tasks uses delegate pattern to call the backend

---

omegaml/__init__.py
omegaml/backends/basecommon.py
omegaml/backends/basemodel.py
omegaml/backends/package/__init__.py
omegaml/backends/package/tasks.py
omegaml/tasks.py

- backend.perform('method') calls backend.method() wrapped by
pre_/post_method calls to allow custom processing by mixins
- backends can override _call_handler to delegate processing
- prepares for openapi signature checks, data mapping

add pre-/post task hooks using common .perform() backend method

---

omegaml/mixins/store/extdmeta.py

- auth: always check string value of apikey, userid provided

streamline extdmetadata handling resp. X, Y, result

---

omegaml/celery_util.py
omegaml/tasks.py
omegaml/tests/core/test_runtime.py

- om.runtime.mode(logging=True) now logs exceptions, as is commonly expected
- om.runtime.model(logging='DEBUG') logs exception with traceback

log exceptions in runtime tasks

---

omegaml/runtimes/proxies/baseproxy.py
omegaml/runtimes/proxies/jobproxy.py
omegaml/runtimes/runtime.py
omegaml/tests/core/test_runtime.py

- locally set require() precedes model attributes, for clarity
- model attributes require kwargs override default runtime

improve runtime require() semantics

---

omegaml/backends/mlflow/models.py
omegaml/mixins/store/imexport.py
omegaml/util.py

fixes failing builds on Python 3.10, 3.11
amends PR #374

backport tarfile.extractall filter to Python < 3.12

---

omegaml/mixins/store/datarevision.py
omegaml/mixins/store/modelversion.py
omegaml/tests/core/test_datarevision.py
omegaml/tests/core/test_imexport.py
omegaml/tests/core/test_modelversions.py

simplify model and dataset revisions
- store.revisions() returns a list of names@tag
- simplifies retrieval of revisions similarly to store.list()

Simplify revisions

---

omegaml/backends/virtualobj.py
omegaml/mixins/store/virtualobj.py
omegaml/tests/core/test_virtualobj.py
omegaml/tests/tensorflow/test_tfestimator.py

this improves portability for `@virtualobj` functions across python versions  
- store source code for functions, classes defined outside `__main__`
- issue a warning if a module is stored that has a `__main__` block

improve virtualobj storing

---

omegaml/store/logging.py
omegaml/tests/core/test_logging.py

- pymongo recursively calls logger.debug(), resulting in recursion on handler.emit()
- fixed by disabling pymongo debug logging

fix recursion issue due to pymongo 4.7

---

omegaml/backends/restapi/service.py
omegaml/backends/sqlalchemy.py
omegaml/client/userconf.py
omegaml/mixins/store/extdmeta.py
omegaml/mixins/store/modelversion.py
omegaml/runtimes/proxies/baseproxy.py
omegaml/runtimes/runtime.py
omegaml/store/base.py
omegaml/store/filtered.py
omegaml/store/query.py
omegaml/store/queryops.py
omegaml/tests/core/restapi/test_service_api.py
omegaml/tests/core/test_filtered_collection.py
omegaml/tests/core/test_sqlalchemy.py
omegaml/util.py

- in /service rest api, raise native exceptions as returned
- in datasets (mongodb and sqlalchemy) enable passing trusted filter kwargs, disabling injecting testing. trusted queries require a locally and salted hash of the filter kwargs, only available to local and interactive code
- allow local testing in test mode only
- support more types in mongo json encoder

enhance input/output validation

---

.gitignore

- avoid storing clear text keys

ignore local mongoinit.js

---

omegaml/defaults.py

- env OMEGA_WORKER_CONCURRENCY sets celery worker concurrency
- defaults to 4 to avoid worker cpu overload in light of 8, 12 core machines used more often
- set to -1 to set to os.cpu_count(), i.e. all available cores

allow setting worker concurrency from env

---

omegaml/__init__.py
omegaml/client/lunamon.py
omegaml/omega.py
omegaml/runtimes/runtime.py
omegaml/tests/core/test_lunamon.py
omegaml/util.py

- this adds a background monitor of services (e.g. mongodb, rabbitmq)
- useful for checking status of services without delay and alerting users to problems, e.g. in a web ui
- adds `om.status()` for easier checking by user

add background monitor of services

---

omegaml/defaults.py
omegaml/mongoshim.py
omegaml/store/base.py

- since PyMongo 4.10 connection timeouts are specified differently for connection, socket and server selection
- use the same timeout settings for all to get comparable fast timeouts

chore: fix mongodb connection timeout

---

omegaml/notebook/jobs.py
omegaml/notebook/jobschedule.py
omegaml/tests/core/test_jobs.py

- om.jobs.schedule works as expected
- parses natural language spec more reliably
- removes previously scheduled jobs

chore: improve job scheduling semantics

---

omegaml/__init__.py
omegaml/defaults.py
omegaml/mixins/store/objinfo.py
omegaml/store/base.py
omegaml/store/combined.py
omegaml/store/streams.py
omegaml/tests/core/test_objinfo.py
omegaml/tests/core/test_store.py
omegaml/tests/util.py
omegaml/util.py

- om.stats(), store.stats() provide storage object information
- improve om top-level module ux: om.buckets(), om.list(), om.stats(), om.metadata(), om.help()
- mixins now provide the base cls name instead of the top-level (improves help())

Add store objinfo

---

omegaml/backends/tracking/base.py
omegaml/backends/tracking/experiment.py
omegaml/backends/tracking/simple.py
omegaml/backends/tracking/statistics.py
omegaml/tests/core/test_tracking.py
omegaml/util.py

- tracker.data() supports run=<slice> to specify a range of runs
- tracker.stats.metrics() are computed by run, not all runs by default

feat: enable sliced query of tracking data, improve stats

---

omegaml/backends/genai/textmodel.py
omegaml/util.py

- all calls with a converation_id to TextModel.complete() will track usage
- in tracking dataset: event: usage, key: actual metric, value: metric value, conversation_id: the conversation id
closes #518

enable usage tracking on calls to chat.completions provider endpoint
