- Dockerfile
- docker-compose.yml
- omegaml/client/cloud.py
- omegaml/defaults.py
- omegaml/example/userext/mymodule.py
- omegaml/tasks.py
- scripts/devtest.sh
- scripts/docker/jyhub/Dockerfile
This enables user extensions by
- /app/config.yml 
- USER_EXTENSIONS configuration option to easily add plugins (mixins and backends)
see config-example.yml for an example
> Enable userextensions

- omegaml/defaults.py
- omegaml/mdataframe.py
- omegaml/mixins/mdf/__init__.py
- omegaml/mixins/mdf/apply.py
- omegaml/mixins/mdf/applyutil.py
- omegaml/mixins/mdf/parallel.py
- omegaml/runtimes/locky.py
- omegaml/store/filtered.py
- omegaml/tests/test_mdfparallel.py
this integrates the omx_transform plugin, supporting out-of-core native Pandas parallel processing https://gist.github.com/omegaml/865fa51adbb030ae416fa60ec9bfefa2
```
def myfunc(df):
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
mdf = om.datasets.getl('very-large-dataframe')
mdf.transform(myfunc).persist('transformed-dataframe')
```
Learn more https://gist.github.com/omegaml/fd26783f03c0b7fd490ca951474e6e39
> Integrate omxtransform

- omegaml/backends/__init__.py
- omegaml/backends/basecommon.py
- omegaml/backends/basedata.py
- omegaml/backends/basemodel.py
- omegaml/backends/keras.py
- omegaml/backends/npndarray.py
- omegaml/backends/package/__init__.py
- omegaml/backends/rawfiles.py
- omegaml/backends/scikitlearn.py
- omegaml/backends/tensorflow/protobufobj.py
- omegaml/backends/tensorflow/tfestimatormodel.py
- omegaml/backends/tensorflow/tfsavedmodel.py
- omegaml/backends/virtualobj.py
- omegaml/defaults.py
- omegaml/documents.py
- omegaml/mixins/mdf/apply.py
- omegaml/notebook/jobs.py
- omegaml/store/base.py
- omegaml/tests/test_mdfmixins.py
- omegaml/tests/test_store.py
> refactor filestorage to use same approach across all plugins

- omegaml/backends/scikitlearn.py
- omegaml/defaults.py
- omegaml/mdataframe.py
- omegaml/mixins/store/__init__.py
- omegaml/mixins/store/lazyget.py
- omegaml/mixins/store/projected.py
- omegaml/mixins/store/virtualobj.py
- omegaml/tests/test_runtime.py
- omegaml/tests/test_store.py
> enable implicit chunking by yielding an iterable from dataset name

- .circleci/config.yml
- omegaml/tests/features/util.py
the default version is still tensorflow 2.2.0
> enable tensorflow 2.3.0 (unit testing)

- omegaml/backends/restapi/script.py
- omegaml/client/cli/jobs.py
- omegaml/client/userconf.py
- omegaml/notebook/jobs.py
- omegaml/notebook/omegacontentsmgr.py
- omegaml/store/base.py
- omegaml/tests/test_contentsmgr.py
- omegaml/tests/test_store.py
BEWARE changing Omega for OmegaCloud is inteferring with loading and
dependency injection mechanism.
> updates for stability and increased performance

- omegaml/mdataframe.py
- omegaml/tests/test_mdataframe.py
> fix merge duplicate keys exception, enable filter on joined collections

- omegaml/backends/rawdict.py
- omegaml/client/cli/jobs.py
- omegaml/defaults.py
- omegaml/mdataframe.py
- omegaml/mixins/mdf/filterops.py
- omegaml/notebook/jobs.py
- omegaml/runtimes/loky.py
- omegaml/store/base.py
- omegaml/store/fastinsert.py
- omegaml/store/filtered.py
- omegaml/store/query.py
- omegaml/tests/test_mdataframe.py
- omegaml/tests/test_store.py
- omegaml/util.py
> Various improvements

- omegaml/omega.py
- omegaml/store/combined.py
- omegaml/tests/test_store.py
> Combined store

- omegaml/backends/externaldata.py
- omegaml/mdataframe.py
- omegaml/mixins/mdf/apply.py
- omegaml/mixins/store/promotion.py
- omegaml/notebook/jobs.py
- omegaml/store/base.py
- omegaml/store/queryops.py
- omegaml/tests/test_jobs.py
- omegaml/tests/test_promotion.py
- omegaml/tests/test_store.py
- omegaml/util.py
- enable https for pandas external data
- enable pandas.read_csv kwargs to be stored in meta data
- ensure FilteredCollection is used in apply cursor
- enable selective dropping of target object on promote, supporting
multi-version model promotion
- align prefix and bucket handling on OmegaJobs to OmegaBase store
- use ensure_index on DataFrame storing, align with
MDataFrame.create_index
> fixing several bugs

- omegaml/store/logging.py
- enable easy tracking of arbitrary logs
> enable tracking of arbitrary logs via cli

- omegaml/client/cli/cloud.py
- omegaml/client/userconf.py
- omegaml/client/util.py
- omegaml/sklext.py
- omegaml/store/logging.py
- omegaml/tests/test_sklext.py
- setup.py
this extends the cli to display cluster status in summary form
- runtime (celery)
- dbsize (mongodb)
- pods
- nodes
> enable cli cloud status report and pod log access

- docs/source/guide/filterdf.rst
- omegaml/mixins/mdf/filterops.py
closes https://github.com/omegaml/omegaml/issues/141
> Fix filterops

- omegaml/client/cli/__init__.py
- omegaml/client/cli/runtime.py
- omegaml/client/cli/shell.py
- omegaml/client/util.py
- omegaml/runtimes/envinstall/envinstall/__init__.py
- omegaml/runtimes/envinstall/setup.py
- omegaml/runtimes/runtime.py
- omegaml/store/base.py
* add self-contained remote env install 
* enable runtime status view
* enable running python code directly on om shell call
> Enable worker utilities

- omegaml/client/cli/cloud.py
- omegaml/client/cli/runtime.py
- omegaml/client/cli/scripts.py
- omegaml/client/util.py
* simplify runtime and scripts
require valid config file for all om cloud commands
closes #145
* fix unit conversion on node status
> Refactor cli

- omegaml/defaults.py
- omegaml/store/base.py
- omegaml/store/logging.py
- omegaml/store/queryops.py
- omegaml/tests/test_runtime.py
- omegaml/tests/test_store.py
- omegaml/util.py
> Enable long dataset names

- omegaml/client/cli/runtime.py
- omegaml/omega.py
- omegaml/runtimes/runtime.py
- omegaml/tests/features/util.py
minor technical updates to enable vendor neutral cloud deployments
> Enable apphub dedicated cluster

- Makefile
- docker-compose-dev.yml
- omegaml/backends/package/localpip.py
- omegaml/celery_util.py
- omegaml/client/cli/scripts.py
- omegaml/defaults.py
- omegaml/mixins/store/lazyget.py
- omegaml/notebook/jobs.py
- omegaml/notebook/tasks.py
- omegaml/runtimes/jobproxy.py
- omegaml/runtimes/runtime.py
- omegaml/store/logging.py
- omegaml/tasks.py
- omegaml/tests/test_jobs.py
- omegaml/tests/test_logging.py
- omegaml/tests/test_nbtasks.py
- omegaml/tests/test_runtime.py
- omegaml/util.py
- setup.py
6d47835 add configuration from env var to be in cluster
abdb2b1 fix passing None as a name on get
f96d93f add copying scripts to a localpath
eb5102f allow timeout parameter to be passed on job.run
c74f4fe fix pandas 1.0 import, keras version limits
> several updates

- omegaml/store/base.py
> Enable mongodb srv uris

- omegaml/client/cli/cloud.py
- omegaml/omega.py
- omegaml/runtimes/runtime.py
- setup.py
39aa3b2 enance/fix erronous cli handling
a3c6df9 simplify client only install
> minor maintenance items

- .circleci/config.yml
- docker-compose.yml
- docs/source/guide/advanced/scripts/mlflow.rst
- docs/source/nb/omegaml-tutorial.ipynb
- omegaml/backends/mlflow/gitprojects.py
- omegaml/notebook/jupyter/jupyter_notebook_config.py
- omegaml/notebook/jupyter/jupyter_server_config.py
- omegaml/restapi/__main__.py
- omegaml/tests/mlflow/test_mlflow_projects.py
- scripts/rundev.sh
- scripts/runtime/omegajobs.sh
- setup.py
- upgrade jupyterhub
- adjust jupyter server and notebook configuration
- clarify PORT env variable
- align jupyterhub startup with commercial edition requirements
-
> upgrade dependencies

- omegaml/client/cli/cloud.py
- omegaml/client/cloud.py
- omegaml/client/userconf.py
- omegaml/omega.py
- scripts/runtests.sh
qualifier can be specified in `om cloud login`
> Simplify qualifiers

- omegaml/defaults.py
- omegaml/store/fastinsert.py
- omegaml/util.py
pending migration to pymongo 4.1, https://jira.mongodb.org/browse/PYTHON-2585
> upgrade pymongo 4.1

- omegaml/mixins/store/imexport.py
- setup.py
- fix - Windows and Linux tar tools cannot handle filenames with :
- fix - nbconvert Jinja <3 dependency is no longer required
> fix compressed export filename

- omegaml/backends/package/localpip.py
- omegaml/backends/package/packager.py
- omegaml/client/cli/__init__.py
- omegaml/example/demo/callback/setup.py
- omegaml/tests/core/test_package.py
- setup.py
- remove tee dependency as it has started to cause logging issues
- replace distutils with setuptools
- simplify package semantics
> refactor package build

- omegaml/backends/experiment.py
- omegaml/store/migrations/0001_upgrade_tracking.py
- omegaml/store/migrations/__init__.py
- omegaml/tests/core/test_tracking.py
- move tracking dataset from md.attributes['dataset'] to
md.attributes['tracking']['dataset']
- add basic migrations to support easy transition
> refactor tracking dataset metadata

- omegaml/defaults.py
- omegaml/tests/mlflow/test_mlflow_projects.py
- temporarily disable mlflow remote project tests due #258
> Fix mlflow gitissue

- omegaml/mixins/store/extdmeta.py
- omegaml/store/base.py
- omegaml/tests/core/test_extdmeta.py
- omegaml/util.py
- setup.py
> win10.x compatibility

- .circleci/config.yml
- setup.py
- use latest circleci ubuntu 20.04 LTS image
> python 3.10 build support

- omegaml/store/logging.py
- om.logger.show() is a simpler interface to om.logger.dataset
- om.logger.show() => print latest 20 rows in pandas dataframe
- om.logger.show(wait=True) => tail log
> simplify logger access

- omegaml/mixins/store/extdmeta.py
- omegaml/tests/core/test_extdmeta.py
- move link_swagger from previously ee-only to ce
> extend swagger api mapping 

- omegaml/mixins/store/imexport.py
- omegaml/util.py
- enable absolute windows paths in export archives
> improve windows compatibility

- omegaml/client/userconf.py
- omegaml/defaults.py
- omegaml/tests/core/test_configs.py
- omegaml/util.py
- the config file was not read for the local worker
> load config file for local in-memory worker

- omegaml/runtimes/modelproxy.py
- omegaml/runtimes/trackingproxy.py
- omegaml/tests/core/test_tracking.py
> ensure om.runtime default tracking is applied

- omegaml/celery_util.py
- omegaml/client/auth.py
- omegaml/runtimes/runtime.py
* baseline to close https://github.com/omegaml/omegaml-enterprise/issues/363
> Enable celery monitoring hook

- omegaml/documents.py
- workaround to mongoengine issue https://github.com/MongoEngine/mongoengine/issues/2502
> allow read-only mongodb user

- omegaml/backends/sqlalchemy.py
- omegaml/tests/core/test_sqlalchemy.py
- prepare sql statements with variables using bound variables
- "select ... where T.col={var}" => "select * from T where T.col=:var"
- this avoids sql injection attacks
- double quoted vars "{{vars}}" can be used for sanitized input
- a warning is generated for unsanitized var replacement
> use sqlalchemy prepared statements for pd.read_sql

- omegaml/defaults.py
- omegaml/mongoshim.py
- omegaml/runtimes/runtime.py
- enable mongodb backend for persistent, multi-client task results
- ensure derived mongo_url is compatible with pymongo 4.x
> enable using mongodb as a result backend

- omegaml/client/cli/runtime.py
- omegaml/client/util.py
- omegaml/runtimes/runtime.py
- setup.py
> Upgrade celery 5

- omegaml/backends/experiment.py
- omegaml/defaults.py
- omegaml/mixins/store/lazyget.py
- omegaml/mixins/store/passthrough.py
- omegaml/runtimes/mixins/modelmixin.py
- omegaml/tests/core/test_passthrough.py
- PassthroughDataset implements an in-memory representation of small datasets
- considered an internal feature for performance optimization purpose
> enable small datasets to be passed as part of the message

- omegaml/backends/sqlalchemy.py
- address a common issue with sqlalchemy connection strings https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls
- fixes #315
> ensure sql connection string secrets are properly encoded

- docker-compose-dev.yml
- docker-compose.yml
- scripts/docker/livetest/docker-compose.yml
- https://endoflife.date/rabbitmq
> upgrade rabbitmq to latest release

- omegaml/notebook/omegacontentsmgr.py
- setup.py
- dependencies to notebook are now nbclassic
- https://pypi.org/project/nbclassic/
> refactor jupyterlab 4.0 dependency to nbclassic

- setup.py
- due to https://github.com/pandas-dev/pandas/issues/57049
> pin pandas dependency to circumvent sqlite testing issue

- .circleci/config.yml
- circle-ci advice https://circleci.com/developer/machine/image/ubuntu-2204
> upgrade circle-ci image

- omegaml/backends/basemodel.py
- omegaml/backends/runtime/preload.py
- omegaml/mixins/store/cached.py
- omegaml/runtimes/envinstall/envinstall/__init__.py
- omegaml/tasks.py
- omegaml/tests/core/test_cached.py
- omegaml/util.py
- setup.py
> enable objects preloading and caching

- omegaml/backends/mlflow/models.py
- omegaml/tests/mlflow/test_mlflow_models.py
- mlflow projects can be versioned again
> Fix mlflow project recreate

- omegaml/backends/tracking/simple.py
- omegaml/tests/core/test_tracking.py
- omegaml/util.py
- TrackingProvider.data(batchsize=N) returns batches of data
> TrackingProvider now allows for batching of data retrieval

- Makefile
- scripts/runtime/setup-r.sh
- R installation is dynamic relative omegaml package root
> update R installation

- omegaml/store/streams.py
`om.stream.put()` returns Metadata object for consistency
> improve om.streams semantics

- omegaml/mixins/store/datarevision.py
- omegaml/tests/core/test_datarevision.py
> fix tracking fails on added columns

- Makefile
- scripts/secdev/.snyk-code-test.report
- scripts/secdev/scanned-pipreqs.txt
upgrades due to dependabot alerts
- tqdm https://github.com/omegaml/omegaml/security/dependabot/577
- werkzeug https://github.com/omegaml/omegaml/security/dependabot/578
- jinja https://github.com/omegaml/omegaml/security/dependabot/579
> dependency updates

- omegaml/client/auth.py
- omegaml/tests/core/test_configs.py
> AuthenticationEnv.prepare_env() sets None value as blank

- omegaml/mongoshim.py
disables pymongo's noisy messages for server selection
> disable monogdb logging on startup

- omegaml/defaults.py
- omegaml/omega.py
- omegaml/util.py
- reduce perceived loading wait time
> add loading progress spinner

- omegaml/client/cli/runtime.py
- pd.option display.maxcolwidth must be either -1 (max) or a positive int
> fix pandas 2.x compatibility

- omegaml/runtimes/envinstall/setup.py
> fix envinstall pip error

- omegaml/defaults.py
- omegaml/omega.py
- omegaml/util.py
- setup.py
- speeds up initial loading of omegaml module by deferring framework loading
> speedup omega base loading

- docs/source/guide/monitoring/index.rst
- omegaml/backends/basemodel.py
- omegaml/backends/keras.py
- omegaml/backends/monitoring/__init__.py
- omegaml/backends/monitoring/alerting.py
- omegaml/backends/monitoring/base.py
- omegaml/backends/monitoring/datadrift.py
- omegaml/backends/monitoring/modeldrift.py
- omegaml/backends/monitoring/stats.py
- omegaml/backends/scikitlearn.py
- omegaml/backends/tensorflow/tfestimatormodel.py
- omegaml/backends/tensorflow/tfsavedmodel.py
- omegaml/backends/tracking/base.py
- omegaml/backends/tracking/simple.py
- omegaml/backends/tracking/statistics.py
- omegaml/backends/virtualobj.py
- omegaml/celery_util.py
- omegaml/defaults.py
- omegaml/mixins/store/tracking.py
- omegaml/runtimes/proxies/modelproxy.py
- omegaml/runtimes/proxies/trackingproxy.py
- omegaml/runtimes/runtime.py
- omegaml/store/filtered.py
- omegaml/store/queryops.py
- omegaml/tests/core/test_filtered_collection.py
- omegaml/tests/core/test_monitoring.py
- omegaml/tests/core/test_tracking.py
- omegaml/tests/util.py
- omegaml/util.py
- enables automatic drift monitoring on datasets and models
- extensible architecture with a default ready-to-use implementation + ability to integrate any other drift library
- separation of concerns for snapshots, drift detection and alerting
- common UX
> add automatic drift monitoring

- omegaml/client/lunamon.py
- omegaml/omega.py
- omegaml/store/logging.py
- omegaml/tests/core/test_lunamon.py
- omegaml/util.py
- fix latent ci issue caused by LunaMonitor not stopping
> feat: add background monitor

- .circleci/config.yml
- docker-compose-dev.yml
- omegaml/store/base.py
- omegaml/tests/core/cli/test_cli_runtime.py
- omegaml/util.py
- scripts/initlocal.sh
- scripts/mongoinit.js.example
- setup.py
- mongodb >= 7.0
- rabbitmq >= 3.12
- pymongo >= 4.10
> chore: upgrade mongodb, rabbitmq

- omegaml/mixins/store/virtualobj.py
- omegaml/tests/core/test_store.py
> fix: replace datasets when requested

- omegaml/client/cli/cloud.py
- fixes issue with command line parsing for mongodump/mongorestore
> Fix mongodump

- omegaml/backends/tracking/simple.py
- omegaml/tests/core/test_tracking.py
- omegaml/util.py
> Experiment tracking data() datetime range query

- omegaml/backends/tracking/simple.py
- pkg_resources is deprecated, see https://discuss.python.org/t/pkg-resources-is-deprecated-warning/59517
> chore: remove pkg_resources dependencies

- docker-compose-dev.yml
- docker-compose.yml
- fixes some mongo image references were still on 5.x
> chore: ensure all mongo references are on 7.x

- omegaml/client/lunamon.py
- omegaml/omega.py
- omegaml/runtimes/runtime.py
- omegaml/tests/core/test_events.py
- omegaml/tests/core/test_runtime.py
- setup.py
- om.status() optionally waits for connections, can return single or all check status
- om.runtime.status() returns live cluster status
> feat: om.status(), om.runtime.status() improved monitoring

- omegaml/backends/basemodel.py
- omegaml/backends/monitoring/base.py
- omegaml/backends/monitoring/stats.py
- omegaml/backends/tracking/base.py
- omegaml/backends/tracking/profiling.py
- omegaml/backends/tracking/simple.py
- omegaml/celery_util.py
- omegaml/mixins/store/tracking.py
- omegaml/runtimes/proxies/baseproxy.py
- omegaml/store/logging.py
- omegaml/tests/core/test_misc.py
- omegaml/tests/core/test_tracking.py
- omegaml/tests/tensorflow/test_tftracking.py
- fix minor issues
- improve ux
> chore: improve tracking, monitoring api stability

- omegaml/client/cli/shell.py
- omegaml/store/streams.py
- omegaml/tests/streams/test_streams.py
- match minibatch latest release
> improve minibatch compat

- omegaml/backends/tracking/experiment.py
> fix: ensure subpath in experiment name is preserved in dataset

- omegaml/client/lunamon.py
- reduce runtime checks timeout to .1 seconds
> chore: faster lunamon checks

- omegaml/backends/monitoring/base.py
- omegaml/backends/monitoring/modeldrift.py
- omegaml/backends/monitoring/stats.py
- omegaml/store/base.py
- omegaml/tests/core/test_monitoring.py
- omegaml/tests/util.py
- add kld, jsd, psi statistics
- drift score calculated on 0..1 scale specific for each statistic
- stabilize stats api, enable returning plot data instead of plots
- update mon tests
> feat: add more drift statistics

- omegaml/client/cli/runtime.py
- fixes use of om runtime deploy --select <filter>
> fix: enable cli runtime deploy task selection

- omegaml/mdataframe.py
- omegaml/mixins/store/objinfo.py
- omegaml/notebook/tasks.py
- omegaml/runtimes/mixins/swagger/helpers.py
- omegaml/runtimes/proxies/modelproxy.py
- omegaml/store/base.py
- omegaml/store/queryops.py
- omegaml/tests/util.py
- omegaml/util.py
- OmegaStore.objinfo() improve error message, adopt to mongo 4.0
- job scheduling now includes hidden jobs
- swagger error message fixes // double slash
- runtime.model().monitor() returns defined monitor for a model
- various error message updates
- mdataframe clone includes parser
- yaspin is failsafe and more adaptive to env it runs in (only interactive + jupyter)
> chore: various updates

- omegaml/backends/tracking/__init__.py
- omegaml/backends/tracking/base.py
- avoid excessive memory use by loading tensorflow without need
> chore: tensorflow is lazy-loaded

- omegaml/notebook/checkpoints.py
- setup.py
- Ipython 9.0 removed deprecated features
> chore - fix ipython dependency issue

- omegaml/celery_util.py
- omegaml/example/demo/callback/README
- setup.py
- closes #477, resolves regression introduced by celery/celery#9208
> chore: support celery 5.5

- docs/source/changes/v0.16.4.rst
this adds the 0.16.4 changes to docs
> docs: add changes 0.16.4

- docker-compose-dev.yml
- omegaml/backends/genai/__init__.py
- omegaml/backends/genai/embedding.py
- omegaml/backends/genai/index.py
- omegaml/backends/genai/inmemory.py
- omegaml/backends/genai/models.py
- omegaml/backends/genai/mongovector.py
- omegaml/backends/genai/pgvector.py
- omegaml/backends/genai/textmodel.py
- omegaml/backends/restapi/model.py
- omegaml/backends/restapi/service.py
- omegaml/backends/virtualobj.py
- omegaml/defaults.py
- omegaml/mixins/store/modelversion.py
- omegaml/mixins/store/virtualobj.py
- omegaml/runtimes/mixins/modelmixin.py
- omegaml/server/dashboard/BOOTEY-LICENSE.md
- omegaml/server/dashboard/app.py
- omegaml/server/dashboard/templates/dashboard/genai/chat.html
- omegaml/server/dashboard/views/genai/__init__.py
- omegaml/server/restapi/resources.py
- omegaml/tasks.py
- omegaml/tests/__init__.py
- omegaml/tests/core/restapi/test_completion.py
- omegaml/tests/genai/test_embedding.py
- omegaml/tests/genai/test_genai.py
- omegaml/tests/genai/test_pgvector.py
- setup.py
feature implementation of generative AI support; this is a refactor of work started in 2023, and completed based on recent insights
closes #475
> enable core gen ai features

- .circleci/config.yml
- FUNDING.yml
- docs/requirements.txt
- omegaml/util.py
- automatically make an publish multihtml docs
- fix a ci build issue when mlflow is not installed
> ci: publish latest docs to gh-pages

- omegaml/store/base.py
- omegaml/tests/core/test_store.py
> Fix multiindex columns

- omegaml/backends/genai/__init__.py
- omegaml/backends/genai/textmodel.py
- omegaml/backends/tracking/simple.py
- omegaml/tests/genai/test_genai.py
- preparation for #493 to enable pipeline tracing
> use tracking as the model conversation log

- README.rst
- fix readme link to medium article
> fix: readme links
